apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorchjob-fmnist"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: mavencodev/pytorchjob:1.0
              args:
                - --epochs
                - --seed
                - --log-interval
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              # modify this property if you like to use a custom image
              image: mavencodev/pytorchjob:1.0
              args:
                - "--epochs=6"
                - --seed
                - --log-interval